export { BaseMagic } from './base-magic';
export type { BaseMagicData } from './base-magic';
export { MagicAttack } from './magic-attack';
export type { MagicAttackData } from './magic-attack';
export { MagicAuxiliary } from './magic-auxiliary';
export type { MagicAuxiliaryData } from './magic-auxiliary';
export { MagicEnhance } from './magic-enhance';
export type { MagicEnhanceData } from './magic-enhance';
export { MagicRestore } from './magic-restore';
export type { MagicRestoreData } from './magic-restore';
export { MagicSpecial } from './magic-special';
export { ResMagicChain } from './res-magic-chain';
export type { ResMagicChainData } from './res-magic-chain';
