#pragma once

#include "resource.h"

typedef enum _FIXED_WINDOW {
	FIEXD_NONE = 0,
	FIEXD_TOPLEFT,
	FIEXD_TOPRIGHT,
	FIEXD_BOTTOMLEFT,
	FIEXD_BOTTOMRIGHT,
	FIEXD_LEFTCENTER,
	FIEXD_RIGHTCENTER,
	FIEXD_TOPCENTER,
	FIEXD_BOTTOMCENTER,
}FIXED_WINDOW;